# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7e05f0ef14d5c572dc0d38c0ea391f7f0eba8e54fbf0d7e341b1bc22dd7ada8f9a5e08e5524615472e59ae70030e631e287d771a6affe356d1faf64c60900011

test:
  secret_key_base: 59049895b35e4f9168f972fceb2075720bf4043dfd495a0d9f99af097c345b752d2c3df0b95321da591f0f25f98a9e8687185f83cbb872a42813363bc22be581

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
